### PR TITLE
Add cache for collections

### PR DESCRIPTION
**Pull request by mmacata**
With this PR, the response to `/collections` is cached directly in the openeo-grassgis-driver without the need for nginx or similar to handle the cache.
The cache will be filled on application startup and can be cleared with `/collections?cache=false`

Related to https://github.com/Open-EO/openeo-grassgis-driver/pull/85

### CODE REVIEW

**Review by metzm — COMMENTED** [review]
It seems that the cache is not filled at application startup, but when the endpoint `/collections` is used for the first time after startup. Is this correct? In this case it would be nice if the collections cache would be already filled on application startup.

**Comment by mmacata** [comment]
Yes this is correct. I wanted to avoid a long startup time, because processes are fetched on startup as well. When it takes too long the application never starts but runs in a timeout. The way it is now, the whole application would not be affected and there is more time for collections to be collected. I would prefer to keep it this way and maybe add a persistent file based or redis cache in the future which survives a restart of the application.

**Comment by metzm** [comment]
> [...] I would prefer to keep it this way and maybe add a persistent file based or redis cache in the future which survives a restart of the application.

Very good idea, makes sense.

**Review by metzm — APPROVED** [review]
Ready for merging IMHO.

**Pull request merged**
